### ISSUE TITLE
Discuss with the team the WLinux minimum Windows version 16215

### ISSUE THREAD

**Issue by crramirez** [crramirez/WLinux#11]
In the Windows Fall Creators Update there wasn't support for Linux sockets, so we must discuss what happens with people using this Windows version. Will enable the support asking the user to enable the TLS port? how we can test in this version?

**Comment by sirredbeard** [comment]
The target minimum version is 16299, so do we need to worry about that?

It actually was 17134 but some reason that caused problems even on 17134+ so I had to rebase back to 16299.

**Comment by crramirez** [comment]
The version 17134.5 was the first to introduce Unix Sockets. Due to Wlinux version requirements are lower, we need to deal with the case that the user's Windows version doesn't support Unix sockets
